version: "3.1"

services:
  db:
    image: postgres:17
    container_name: tpv_db
    restart: always
    environment:
      POSTGRES_USER: tpv
      POSTGRES_PASSWORD: tpv
      POSTGRES_DB: tpv_sistema
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persistencia de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script inicial opcional

  adminer:
    image: adminer:latest
    container_name: tpv_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

volumes:
  postgres_data:
